# Change these first
owner: alexkuang0 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Homepage
    url: https://alex0.dev
  - name: Blog
    url: https://blog.alex0.dev
  - name: RSS
    url: https://rss.alex0.dev
  - name: Cloud Sync
    url: https://cloud.alex0.dev

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.alex0.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://img.alex0.dev/avatar.jpg
  name: Alex Web Status
  introTitle: "Status page for Alex Kuang's websites."
  introMessage: "I host websites on different platforms: GitHub/Coding.net pages, PHP shared hosting services, Vercel, Netlify, Firebase Hosting and VPS."
  navbar:
    - title: Status
      href: /
    - title: Alex Kuang
      href: https://alex0.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
